Feat/sort imports
hugsmidjan/hxmstyle pull request #3
Opened 2021-12-08 15:51 UTC by mikaeleli

Added plugins and rules for sorting and removing unused imports

Example input:
```typescript
import { useNotifications } from 'store/useNotifications/useNotifications';
import { SearchPage } from 'pages/Search'; // UNUSED

import {
  BrowserRouter as Router,
  Redirect,
  Route,
  Switch,
} from 'react-router-dom';
import { useMount } from 'react-use';

import { NotificationDrawer } from 'containers/NotificationDrawer';
import { NotificationToasts } from 'containers/NotificationToasts';

import { ErrorBoundary } from 'components/UI/ErrorBoundary';
import { useOrder } from 'store/useOrder';
import { Splashscreen } from 'components/UI/Splashscreen';
import { Layout } from 'containers/Layout';

import { ComponentType, Suspense } from 'react';

import { ProtectedRoute } from 'hocs/ProtectedRoute';
import { Auth } from 'pages/Auth';

import { Customer } from 'pages/Customer';
import { useAuth } from 'store/useAuth';

import './setupDayjs';
```

Example output:
```typescript
import { ComponentType, Suspense } from 'react';
import {
  BrowserRouter as Router,
  Redirect,
  Route,
  Switch,
} from 'react-router-dom';
import { useMount } from 'react-use';

import { ErrorBoundary } from 'components/UI/ErrorBoundary';
import { Splashscreen } from 'components/UI/Splashscreen';
import { Layout } from 'containers/Layout';
import { NotificationDrawer } from 'containers/NotificationDrawer';
import { NotificationToasts } from 'containers/NotificationToasts';

import { ProtectedRoute } from 'hocs/ProtectedRoute';
import { Auth } from 'pages/Auth';
import { Customer } from 'pages/Customer';
import { useAuth } from 'store/useAuth';
import { useNotifications } from 'store/useNotifications/useNotifications';
import { useOrder } from 'store/useOrder';

import './setupDayjs';
```

2021-12-13 15:25 UTC, Valur commented
LGTM

2021-12-13 15:27 UTC, Valur approved these changes

2021-12-13 17:08 UTC, maranomynet requested changes

2021-12-13 17:08 UTC, maranomynet commented on .editorconfig
> +quote_type = single
FYI, þessi skrá er tæknilega "governed" af hxmstyle (canary branchinu) sem er í pkg.devDependencies í project rótinni.
Allar breytingar á henni eru yfirskrfaðar við næsta update, sbr.

https://github.com/hugsmidjan/hxmstyle/blob/c01dbb9e71d3e961ae5821fc2cb8f8c19d38a1e8/.editorconfig#L1-L4

2021-12-13 17:08 UTC, maranomynet commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0",
Ég myndi almennt halda svona "[dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food)" uppfærslum í sér committi.

2021-12-13 17:08 UTC, maranomynet commented on configs/core.js
> +    "simple-import-sort/exports": "error",
Sterkar efasemdir.
Ólíkt imports, þá eru exports aldrei auto-inserted. Þau eru alltaf ígrunduð viðbót höfundar og röð exporta er allt eins líkleg til að vera skipulögð til að auka læsileika.

Fyrir mér hljómar þetta jafn fráhrindandi og hugmyndin um að raða local breytum í stafrófsröð.

2021-12-13 17:08 UTC, maranomynet commented on configs/core.js
> +    "import/no-duplicates": "error",
Fyrir svona low-impact atriði sem þar að auki auto-fixast onSave þá fer voðalega í taugarnar á mér að fá alltaf rautt "panic! error!" feedback þegar ég er að skrifa.

Setjum þetta á "warn" því þetta kallar ekki á neina aðgerð hjá notandanum.

Sama gildir mögulega um fleiri atriði í þessum reglum.  ...og það má eflaust endurskoða notkun á "error" í  öðrum reglusettum í þessum pakka líka.

2021-12-13 17:08 UTC, maranomynet commented on configs/core.js
> +          ['^\\u0000'],
hmm... eru side-effect imports ekki `@import 'foo';`

Mín reynsla segir mér að þau ættu líklega betur heima **efst** í import röðinni.  
...þó ekki væri nema til að leggja áherslu á vafasama nærveru þeirra.

@oli @kariyngva hvað segið þið?

2021-12-13 17:08 UTC, maranomynet commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0"
Eigum við ekki að hafa þessi nýju deps í stafrófsröð eins og hin?
Just sayin' ;-)

2021-12-13 17:10 UTC, maranomynet commented
@mikaeleli Svo máttu gjarnan splæsa í nokkrar línur í [CHANGELOG.md](https://github.com/hugsmidjan/hxmstyle/blob/v1/CHANGELOG.md?plain=1#L5)

2021-12-13 17:15 UTC, maranomynet commented on .editorconfig
> +quote_type = single
Mér hefur fundist betra að setja slíkar uppfærslur í sér `style:` eða `chore:` commit, til að halda þeim aðskildum frá aksjúal `feat`/`fix` breytingum á library kóðanum.

Dæmi: https://github.com/hugsmidjan/hxmstyle/commit/b2a4876964a5ec16a272bf6fc1c2a51c9cc12306

2021-12-13 18:18 UTC, mikaeleli commented on configs/core.js
> +    "simple-import-sort/exports": "error",
Mig minnir að þetta sé stillt á error til að þetta sé auto-fixað að eslint/prettier við save, ætla samt ekki að hengja mig á það svo ég skal tjekka á þessum plugins betur á morgun 👍

2021-12-13 18:22 UTC, mikaeleli commented on configs/core.js
> +    "simple-import-sort/exports": "error",
Sortering á exports er skipt niður á hópa; notandinn hefur ennþá mikið vald á hvernig því er raðað, sjá [hér](https://github.com/lydell/eslint-plugin-simple-import-sort#exports)

Það má sleppa því mín vegna, hef líklega haft það með á sínum tíma bara því það var í boði 🤡

2021-12-13 18:26 UTC, mikaeleli commented on .editorconfig
> +quote_type = single
aaa svo ég átti bara að breyta `starters/editorconfig.cfg` og keyra svo `dogfood` scriptuna, gotcha!

2021-12-13 18:31 UTC, mikaeleli commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0",
hefði ég þá bara átt að taka fram pakkana í `peerDependencies` og keyra svo `dogfood` scriptuna?

2021-12-14 00:13 UTC, maranomynet commented on configs/core.js
> +    "simple-import-sort/exports": "error",
Hlutir eru auto-fixaðir óháð því hvort þeir séu stilltir á "warn" eða "error"

2021-12-14 00:14 UTC, maranomynet commented on configs/core.js
> +    "simple-import-sort/exports": "error",
Hins vegar hefur það áhrif á hvort non-autofixing lint tékk skili villum og stöðvi build, eða nöldri bara og haldi áfram.

2021-12-14 00:17 UTC, maranomynet commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0",
Já, svo lengi sem þú ert búinn að pusha breytingunum þínum út á `canary` greininni, þá virkar það mjög smooth.

2021-12-14 00:20 UTC, maranomynet commented on .editorconfig
> +quote_type = single
amm. ... en hún sækir sínar uppfærslur frá canary greininni, eins og hún stendur á github, þannig að þú þyrftir að pusha á hana fyrst.

Þetta er oftast eitthvað sem ég geri öðru hvoru megin við release. ...eða enn sjaldnar, enda ekki beint lífsnauðsynlegt að linting/formatting reglur séu öllum stunum uptodate :-)

2021-12-14 13:27 UTC, maranomynet commented
https://github.com/hugsmidjan/hxmstyle/blob/556e7116b021bc07da08f4a862fd8ee05d085fc5/prettier.js#L8-L9

Svo er málið að uppfæra þessa skrá og commenta burt `singleQuote` þannig að það sé pikkað upp úr `.editorconfig`

```js
 // singleQuote: true, 
 semi: true, 
```

2021-12-15 09:56 UTC, kariyngva commented on configs/core.js
> +          ['^\\u0000'],
Tja ég hef ekki sterka skoðun á því, veit ekki afhverju en ég fíla að hafa react import efst, parent/relative og css import neðst. En ég er engu að síður sammála þér með áherslu hlutann.

2021-12-20 12:40 UTC, mikaeleli commented on configs/core.js
> +    "simple-import-sort/exports": "error",
Breytti reglunum í 'warn' 👍 😎

2021-12-20 12:42 UTC, mikaeleli commented on configs/core.js
> +          ['^\\u0000'],
Það má raða hvernig sem er, hef enga sérstaka skoðun á því 🤓

2021-12-20 12:43 UTC, mikaeleli commented on package.json
> +    "eslint-plugin-unused-imports": "^2.0.0"
Klappað og klárt 😎

2021-12-20 14:51 UTC, maranomynet commented on configs/core.js
> +          ['^\\u0000'],
hef enga skoðun  á þessari röð þannig séð, nema að ég hef sterklega á tilfinningunni að side-effect imports skeri sig úr (side-effects-only) og eigi því rétt á því að tróna efst.

Þið getið breytt þessu seinna.

2021-12-20 14:52 UTC, merged